EDITS = [
    ('README.md', '86935c25c450d28a2990818fc9e0d3f83517c6397d4db80595af53d22cfd4556', None, [
        (61, 66, "| Scope | Keys |\n| --- | --- |\n| `aida-admin` | `PUBLIC_BASE_URL`, `SESSION_SECRET`, `DB_HOST`, `DB_NAME`, `DB_USER`, `DB_PASSWORD`, optional `DB_PORT`, `ID_BASE_URL` (and optionally `ID_PUBLIC_BASE_URL`), `ID_CLIENT_SECRET` (only while Identity runs in `secret`/`dual` mode), `ID_TRUSTED_PROXY_CIDRS` |\n| `aida-admin-runtime` | `DB_HOST`, `DB_NAME`, `DB_USER`, `DB_PASSWORD`, optional `DB_PORT` — the separate read-only connection to OfficePulse's runtime database |\n| `aida` | `OFFICEPULSE_API_BASE_URL`, `LIVEKIT_URL`, `LIVEKIT_API_KEY`, `LIVEKIT_API_SECRET` — shared with AidaAgent and OfficePulse |\n| `*` | `PARENT_DOMAIN`, `trustedCIDR`, `ENVIRONMENT_NAME` |\n"),
        (81, 82, '### Database accounts\n'),
        (83, 87, "AidaPlatformDB's `install.sh database` / `install.sh apps` writes canonical\n`DB_HOST`, `DB_NAME`, `DB_USER`, `DB_PASSWORD` and `DB_PORT` rows and provisions\naccounts from those same values. `DB_PASSWORD` is a secret, literal value, not\nURL-encoded; `DB_PORT` defaults to 3306 when omitted.\n\n`app=aida-admin` owns `aida_admin_db` as `aida_admin_app`. Its `DB_*` keys may be\noverridden by the same environment keys, but never fall through to `aida` or `*`.\n`app=aida-admin-runtime` independently describes `aidacalls_db` as `aidaadmin_ro`.\nThe reader resolves only that scope: it cannot inherit Admin's writable credentials\nor OfficePulse's writer. Its DB host/port may differ because the clients can reach\nthe same MySQL server over different network paths. No database URL setting is read.\n\nTo run own-store account provisioning independently, export the resolved\n`app=aida-admin` values and an operator's MySQL admin password:\n"),
        (90, 92, '  -e DB_HOST -e DB_PORT -e DB_NAME -e DB_USER -e DB_PASSWORD \\\n  -e MYSQL_ADMIN_PASSWORD mysql:8.4 bash /scripts/db-users.sh\n'),
        (94, 100, "The script creates `aida_admin_db` and grants its account `ALL PRIVILEGES` only\non that schema. `MYSQL_ADMIN_HOST` / `MYSQL_ADMIN_PORT` optionally change the\noperator's network path without changing app settings. Re-running converges\ngrants; changing `DB_PASSWORD` and re-running rotates the password. The separate\nruntime reader is provisioned through OfficePulse's `scripts/db-users.sh` with\n`SELECT` only. Startup still places its connections in read-only transaction mode.\n\nFor an existing installation, run AidaPlatformDB setup against the updated `dev`\ncheckouts before restarting the apps. Setup copies existing credentials into the\ncanonical rows without replacing nonblank values or rotating passwords. Old rows\ncan then be removed; they are no longer runtime configuration. Both connection\nscopes are required in production. The worker remains API-only and needs no SQL settings.\n"),
    ]),
    ('e2e/runtime.spec.ts', '8147d1fa2df24afc588a2299f5bd64366a7e2b39cf46f195744acf80f46e6d5b', '6cfc6c2da4eaff077188b35094ec3defa1ceaf425895d204375791cd9ce0ebd5', [
        (6, 7, ' * app=aida-admin-runtime DB_* settings and OFFICEPULSE_API_BASE_URL\n'),
    ]),
]
